#+TITLE: Project00 Key_Terms
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+OPTIONS: html-postamble:nil
#+STARTUP: showeverything entitiespretty

NOTE: Be sure, when you are searching that they are logical defintions, that is
they are definitions that relate to math and Logic.

Example
* Superman Cannot be jumping really high
** identify
Superman is sometimes debated around his flying abilities
Some say that he is merely jumping and due to his speed and 
strength it appears to you and I that he is merely jumping and
moving his body to go up and down after that.
** Define
This is obviously false.  Superman is indeed levitating and not
Jumping
** Example/Explanation
If Superman were jumping when he catches Lois Lane she would be cut in half
due to the speed and trajectory of superman being the man of steel. This is because
he would have to slow/stop to the same speed as Lois to catch her and then "rejump".
He visually does not appear to be 'rejumping' and Lois isnt cut in half.  DONE!
** Non-Trivial Test question
What would be the best way to describe Superman's flight


a. He jumps and with his strength and speed is able to alter his path


b. He flys like a bird and flaps his wings


c. He levitates, he's an alien "HEELLLLLOOOO!"


d. Why do I care about Superman again, he's in the D.C. universe ... so dark and terrible movies!

Contrapositive

Converse

inverse

R: real numbers

Z: integers

Q: rational numbers

predicate

Domain

CoDomain

quantifier

antecedent

#+begin_note
  The first half of a hpothetical proposition, whenever the if-clause comes before the then-clause.
#+end_note

consequent

#+begin_note
  The second half of a proposition, whenever it's the then-clause.
#+end_note

Set

#+begin_note
  A collection of objects in which objects are seperate entities.
#+end_note

Fallacy

#+begin_note
  An argument that is not valid (the premises are not true)
#+end_note

biconditional

#+begin_note
  a relationship between two propositions that is true only when both propositions are simultaneously true or false 
#+end_note

sufficient condition

#+begin_note
  Means that the conclusion follows automatically when this condition is met. 
#+end_note

necessary condition

#+begin_note
  A condition that is required to for the conclusion to happen but doesn't mean that it will happen (There could be other requirements needed).
#+end_note

~p

#+begin_note
  The negation of p.
#+end_note

p ^ q

#+begin_note
  The conjunction of p and q. (AND gate)
#+end_note

p ∨ q

#+begin_note
  The disjunction of p and q. (Or gate)
#+end_note

P XOR q

#+begin_note
Exclusive or and symetric difference of p and q. p or q but not both.
#+end_note

p == q

#+begin_note
Logical equivalence.
#+end_note

p -> q

#+begin_note
p is sufficent for q. P is a subset of q.
#+end_note

P <--> q

#+begin_note
biconditional: p if and only if q. P is sufficient for q; and vice versa. True when p and q have the same truth value.
#+end_note

Three dots in a triangle

#+begin_note

#+end_note

upside down A

#+begin_note
Universal quantification. The predication of a property for every member in a domain. Interpreted as: “Given any…” of “For all…”
#+end_note

Backwards E

#+begin_note
Existential quantification. Says “There exists..” or “There’s at least one.”


#+end_note

union

#+begin_note
 Is the set with all the members from two or more sets.
#+end_note

intersection

#+begin_note
Is the set with members in common from two or more sets.
#+end_note

Commutative laws

#+begin_note

#+end_note

associative laws

#+begin_note

#+end_note

distributive laws

#+begin_note

#+end_note

identy laws

#+begin_note

#+end_note

negation laws

#+begin_note

#+end_note

double negative law

#+begin_note

#+end_note

idempotent laws

#+begin_note

#+end_note

universal bound laws

#+begin_note

#+end_note

De morgan's laws

#+begin_note

#+end_note

absoption laws

#+begin_note

#+end_note

negations of t and c

#+begin_note

#+end_note

vacuously true

#+begin_note

#+end_note

Modus Ponens

#+begin_note
  A Latin term for "mode that affirms by affirming".
  In terms of logic; p \rightarrow q , p is t \rightarrow q
  eg: If today is Thursday, the best students will attend discrete mathmatics.
      Today is Thursday! Thus, the best students will attend discrete mathmatics.
#+end_note

Modus Tollens

#+begin_note
  A Latin term for "mode that denies by denying".
  In terms of logic; p \rightarrow q , \neg q \rightarrow \neg p
  eg: If you buy nachoes at the movies, you won't need popcorn.
      You needed popcorn, so you didn't buy the nachoes.
#+end_note

Elimination: valid argument form

#+begin_note
  Using the process of elimanation to show whether something is t or nil.
  p∨q    p∨q
  \neg p    \neg q
  \therefore q   \therefore p
#+end_note

Transitivity: Valid Argument form
#+begin_note
  Transitive reasoning is a valid argument form that allows us to apply the transitive property to logic.
    p \rightarrow q
    q \rightarrow r
  \therefore p \rightarrow r 
  
#+end_note
