#+TITLE: Project00 Key_Terms
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+OPTIONS: html-postamble:nil
#+STARTUP: showeverything entitiespretty

NOTE: Be sure, when you are searching that they are logical defintions, that is
they are definitions that relate to math and Logic.

Example
* Superman Cannot be jumping really high
** identify
Superman is sometimes debated around his flying abilities
Some say that he is merely jumping and due to his speed and 
strength it appears to you and I that he is merely jumping and
moving his body to go up and down after that.
** Define
This is obviously false.  Superman is indeed levitating and not
Jumping
** Example/Explanation
If Superman were jumping when he catches Lois Lane she would be cut in half
due to the speed and trajectory of superman being the man of steel. This is because
he would have to slow/stop to the same speed as Lois to catch her and then "rejump".
He visually does not appear to be 'rejumping' and Lois isnt cut in half.  DONE!
** Non-Trivial Test question
What would be the best way to describe Superman's flight


a. He jumps and with his strength and speed is able to alter his path
** Identify:
Some people are mistaking a change in speed to also mean a change in directon.
Even though a change in speed changes velocity, a change in velocity does not necessarily 
   lead to a change in direction. 
** Define   
Speed does not change direction.
** Example/Explanation 
   Velocity is a combination of speed and direction. One can change speed without
  changing direction. Similarly, direction can be altered without a change in speed. 

b. He flys like a bird and flaps his wings
** Identify:
    Some might think that since superman is mistaken for a bird when he flys,
    he flaps his "wing"s like a bird too.
** Define:
    This is false, superman does not flap his wings like a bird but only
    looks like a bird from far away.
** Example/Explanation
  Whenever superman is in a closeup, he is seen with his arms ourstretched.
** Non-Trivial Test question
  His flying is not based on aerodynamics so it is unecessary for him to flap
  his wings. 

c. He levitates, he's an alien "HEELLLLLOOOO!"
** Identify
  Some believe that superman levitates.
** Define
 This must be true, superman is levitating.
** Example/Explanation
  Since superman's flight is not based on aerodynamics, and he's not jumping, he is levitating.
  In one shot, superman is seen floating in the sky with Louis Lane. 

d. Why do I care about Superman again, he's in the D.C. universe ... so dark and terrible movies!
** Identify 
Some people are forgetting the significance of superman because D.C. makes dark movies and unfortunately
  superman is in the D.C. universe. People are judging superman based on the universe he is in. Since D.C. doesn't make good
  movies, the public would say "What good can come from D.C?"
** Define 
 Judging a character based on their environment is faulty logic. 
** Example/Explanation
Superman was once a beloved hero when he was first created. Superman came about as a personification of America and its role
in World War II. Superman gave people hope and gave something for soldiers and the public to read to forget about their troubles.
I believe that the D.C. universe is a good place for superman to be. His bright costume and good intentions strongly contrast
with D.C.'s dark and hostile flavor.
Take Joseph who was sold to Potipher for example. Joseph, in prison, was in a dark and terrible place. This environment
with all of its temptations made Joseph's riteousness and perseverance all the brighter. 



* Contrapositive
** Define
  Exchanging the hypothesis and conclusion of a conditional statement and negating both.
** Example
   The contrapositive of the statement: "It is raining, so I need an umbrella" is: "I do not need an umbrella, so it is not raining"
   In logical notation this would be. ~q->~p
** Non-Trivial Test Question

* Converse
** Define
  Exchanging the hypothesis and conclusion of a conditional statement.
** Example
   The converse of the statement: "It is raining, so I need an umbrella" is: I need an umbrella, so it is raining."
   In logical notation this would be q->p
** Non-Trivial Test Question

* Inverse
** Define
  The negation of both the hypothesis and conclusion of a conditional statement.
** Example
   The inverse of the statement: "It is raining, so I need an umbrella" is: "It is not raining, so I do not need an umbrella."
   In logical notation this would be ~p->~q
** Non-Trivial Test Question

* R: real numbers
** Define
  Irrational numbers, Rational numbers, Integers, Whole and natural numbers.
** Example
   
** Non-Trivial Test Question

* Z: integers
** Define
   Whole numbers (negative and positive) including zero.
** Example
   {... -3, -2, -1, 0, 1, 2, 3 ...}
** Non-Trivial Test Question

* Q: rational numbers
** Define
   Integers and fractions (numbers between whole numbers).
** Example

** Non-Trivial Test Question

* Predicate
** Define
   A predicate is an expression of one or more variables defined on a domain.
** Example

** Non-Trivial Test Question

* Domain
** Define
   The set of all possible inputs for a function.
** Example
   If we are exploring a function regarding the grades of the students in discrete math, the Domain would be
   the set of the students in the class.
** Non-Trivial Test Question

* CoDomain
** Define
   The set of all possible outputs for a function.
** Example
   If we are exploring a function regarding the grades of the students in discrete math, the Codomain would be
   the possible grades, {F, D-, D, D+, C-, C, C+, B-, B, B+, A-, A}
** Non-Trivial Test Question

* Quantifier
** Define
   The logical symbol which makes an assertion about a set.
** Example
   Two examples of Quantifiers are the Universal Quantifier and the Existential Quantifier.
** Non-Trivial Test Question

* Antecedent
** Define
  The first half of a hypothetical proposition, whenever the if-clause comes before the then-clause.
** Example
   In the statement: "If it is raining, then I will need an umbrella." "If it is raining" is the atecedent.
   In logical notation, this is often referred to as p; as used in the p->q statement, which means if p then q.
** Non-Trivial Test Question

* Consequent
** Define
   The second half of a proposition, whenever it's the then-clause.
** Example
   In the statement: "If it is raining, then I will need an umbrella." "I will need an umbrella" is the consequent.
   In logical notation, this is often referred to as q; as used in the p->q statement, which means if p then q.
** Non-Trivial Test Question

* Set
** Define
   A collection of objects in which objects are seperate entities.
** Example
   The collection of all of the members of the disscrete math class is a set, with each object (student) being a separate entity.
** Non-Trivial Test Question

* Fallacy
** Define
   An argument that is not valid (the premises are not true)
** Example

** Non-Trivial Test Question

* Biconditional
** Define
   A relationship between two propositions that is true if and only if both propositions are simultaneously true or false 
** Example
   A rectangle is a square if and only if it's sides are all the same length.
   In logical notation, p<->q
** Non-Trivial Test Question

* Sufficient Condition
** Define
   Means that the conclusion follows automatically when this condition is met. 
** Example
   Being able to vote is sufficient to say that someone is at least 18.
** Non-Trivial Test Question

* Necessary Condition
** Define
   A condition that is required to for the conclusion to happen but doesn't mean that it will happen (There could be other requirements needed).
** Example
   Being at least 18 is necessary to be able to vote.
** Non-Trivial Test Question

* ~p
** Identify
   The negation symbol, applied to p
** Define
   The logical opposite of the given condition.
** Example
   The negation of the statement "It is raining" is "It is not raining"
** Non-Trivial Test Question

* p ^ q
** Identify
   The conjunction (or intersection) symbol, here applied to p and q.
** Define
   The conjunction is the set of objects that are members of both p and q and the logical
   condition where a conclusion can be true only if both p and q are true.
** Example
   If p is a set of fruit and q is a set of things that are yellow, 
   p ^ q would be the set of things that are both yellow and fruit, such as bananas.
** Non-Trivial Test Question

* p ∨ q
** Identify
   The disjucntion (or union) symbol, here applied to p and q.
** Define
   The disjunction is the set of objects that are members of either p or q and the logical
   condition where a conclusion is true as long as either p or q is true.
** Example
   If p is a set of fruit and q is a set of things that are yellow,
   p V q would be the set of things that are either fruit, yellow, or both.
   Such as apples, bananas, and corn.
** Non-Trivial Test Question

* p XOR q
** Identify
   The exclusive-or or symetric difference operator, here applied to p and q.
** Define
   The symetric difference is the set of objects that are either members of p or members of q,
   but not members of both and the logical condition where the conlusion is true as long as either
   p or q is true, but not both.
** Example
   If p is a set of fruit and q is a set of things that are yellow,
   p XOR q would be the set of things that are either fruit or yellow, but not both.
   Such as Apples and Corn, but not Bananas.

** Non-Trivial Test Question

* p == q
** Identify
   The logical equivalence operator/symbol.
** Define
   The logical equivalence operator states that the operands are the same.
** Example
   If p is a set of fruit, then q is the same set, with all of the same objects within it.
** Non-Trivial Test Question

* p -> q
** Identify
   The implication or if/then logical connective, here applied to p and q.
** Define
   The implication logical connective states that if p is true then q is true, that p is sufficent for q,
   and that p is a subset of q.
** Example
   The statement "If it is raining, then I need an umbrella"
   If p is the set of fruit, q can be the set of produce, which means p is a subset of q.
** Non-Trivial Test Question

* p <--> q
** Identify
   The biconditional, IFF, or if-and-only-if logical connective, here applied to p and q.
** Define
   The biconditional logical connective states that p is true if and only if q is true and
   that p is both necessary and sufficient for q. 
** Example 
** Non-Trivial Test Question

* Three Dots in a Triangle
** Identify
   The Therefore or Conclusion symbol
** Define
   A symbol that denotes "therefore" at the conclusion of a mathmatical proof or logical argument.
** Example
   Rectangles are polygons
   Squares are rectangles
   ∴ Squares are polygons
** Non-Trivial Test Question

* Upside Down A
** Identify
   The Universal Quantifier
** Define
   The Universal Quantifier is given for properties of every member of a domain as in, "For all..." and "Given any..."
** Example
   ∀ x: P(x) means that the function p(x) is true for all values of x in the domain. 
   For all objects in the set of fruit, the sugar content value is greater than 0
** Non-Trivial Test Question

* Backwards E
** Identify
   The Existential Quantifier
** Define
   The Existential Quantifies is given for properties that exist within a domain as in "There exists..." and "There is at least one.."
** Example
   ∃ x: P(x) means that the function p(x) is true for at least one value of x within the domain.
   At least one of the objects in the set of fruit is yellow.
** Non-Trivial Test Question

* Union
** Define
 Is the set with all the members from two or more sets.
** Example

** Non-Trivial Test Question

* Intersection
** Define
Is the set with members in common from two or more sets.
** Example

** Non-Trivial Test Question

* Commutative Laws
** Define
   two valid rules of replacement, allowing the transposition of propositional variables within
   the logical expressions. 
*** Commutativity of Conjunction
   (P ^ Q) <=> (Q ^ P)
*** Commutativity of Disjunction
   (P V Q) <=> (Q V P)
*** Commutativity of Implication (Law of Permutation)
   (P->(Q->R)) <->(Q->(P->R))
*** Commutativity of Equivalence (Complete Commutative Law of Equivalence)
   (P<->Q)<->(Q<->P)
** Example

** Non-Trivial Test Question

* Associative Laws
** Define
 these rules allow one to move parentheses in logical expressions
*** Associativity of Disjunction
 ((P V Q) V R) <-> (P V (Q V R))
*** Associativity of Conjunction
 ((P^Q)^R) <-> (P ^ (Q ^ R))
*** Associativity of Equivalences
 ((P <-> Q) <-> R) <-> (P <-> (Q <-> R))
** Example

** Non-Trivial Test Question

* Distributive Laws
** Define
expand individual occurances of certain logical connectives, within some formula, into
separate applications of those connectives across subformulas of the given formula
*** Distribution of Conjunction Over Conjunction
(P ^ (Q ^ R)) <-> ((P ^ Q) ^ (P ^ R))
*** Distribution of Conjunction Over Disjunction
(P ^ (Q V R)) <-> ((P ^ Q) V (P ^ R))
*** Distribution of Disjunction Over Conjunction
(P V (Q ^ R)) <-> ((P V Q) ^ (P V R))
*** Distribution of Disjunction Over Disjunction
(P V (Q V R)) <-> ((P V Q) V (P V R))
*** Distribution of Implication
(P -> (Q -> R)) <-> ((P -> Q) -> (P -> R))
*** Distribution of Implication Over Equivalence
(P -> (Q <-> R)) <-> ((P -> Q) <-> (P -> R))
*** Distribution of Disjunction Over Equivalence
(P V (Q <-> R)) <-> ((P V Q) <-> (P V R))
*** Double Distribution
((P^Q)V(R^S)) <-> (((PVR)^(PVS))^((QVR)^(QVS)))
((PVQ)^(RVS)) <-> (((P^R)V(P^S))V((Q^R)V(Q^S)))
** Example

** Non-Trivial Test Question

* Identity Laws
** Define

** Example

** Non-Trivial Test Question

* Negation Laws
** Define

** Example

** Non-Trivial Test Question

* Double Negative Law
** Define
\not \not p \equiv p 
** Example

** Non-Trivial Test Question

* Idempotent Laws
** Define
    Anding a variable with 1 OR oring it with 0 will make the one, or 0, insignificant and reduces down to the other variable.
** Example
p \land 1 \equiv p       
p \lor 0 \equiv p
** Non-Trivial Test Question

* Universal Bound Laws
** Define
The intersect of any set with the empty set an the empty set.
The union of any set with the universal set is the universal set.
** Example
A \lor Universal \equiv Universal
A \land emptySet \equiv emptySet
** Non-Trivial Test Question

* De Morgan's Laws
** Define
  A set of transformation rules that apply to boolean logic.
** Example

** Non-Trivial Test Question

* Absorption Laws
** Define
  When a variable in a proposition becomes irrevelent. 
** Example
The set of the union of any set with the universal set is the universal set.  
** Non-Trivial Test Question

* Negations of t and c
** Define
\not t \land \not c 
** Example

** Non-Trivial Test Question

* Vacuously True
** Define
  A statement that asserts that all members in the empty set have a certain
  property. 
** Example

** Non-Trivial Test Question

* Modus Ponens
** Define
  A Latin term for "mode that affirms by affirming".
  In terms of logic; p \rightarrow q , p is t \rightarrow q
** Example
If today is Thursday, the best students will attend discrete mathmatics.
Today is Thursday! Thus, the best students will attend discrete mathmatics.
** Non-Trivial Test Question

* Modus Tollens
** Define
  A Latin term for "mode that denies by denying".
  In terms of logic; p \rightarrow q , \neg q \rightarrow \neg p
** Example
If you buy nachoes at the movies, you won't need popcorn.
      You needed popcorn, so you didn't buy the nachoes.
** Non-Trivial Test Question

* Elimination: valid argument form
** Define
  Using the process of elimanation to show whether something is t or nil.
  p∨q    p∨q
  \neg p    \neg q
  \therefore q   \therefore p
** Example

** Non-Trivial Test Question

* Transitivity: Valid Argument form
** Define
  Transitive reasoning is a valid argument form that allows us to apply the transitive property to logic.
    p \rightarrow q
    q \rightarrow r
  \therefore p \rightarrow r     
** Example

** Non-Trivial Test Question

