#+TITLE: Project00 Key_Terms
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+OPTIONS: html-postamble:nil
#+STARTUP: showeverything entitiespretty

NOTE: Be sure, when you are searching that they are logical defintions, that is
they are definitions that relate to math and Logic.

Example
* Superman Cannot be jumping really high
** identify
Superman is sometimes debated around his flying abilities
Some say that he is merely jumping and due to his speed and 
strength it appears to you and I that he is merely jumping and
moving his body to go up and down after that.
** Define
This is obviously false.  Superman is indeed levitating and not
Jumping
** Example/Explanation
If Superman were jumping when he catches Lois Lane she would be cut in half
due to the speed and trajectory of superman being the man of steel. This is because
he would have to slow/stop to the same speed as Lois to catch her and then "rejump".
He visually does not appear to be 'rejumping' and Lois isnt cut in half.  DONE!
** Non-Trivial Test question
What would be the best way to describe Superman's flight


a. He jumps and with his strength and speed is able to alter his path
** Identify:
Some people are mistaking a change in speed to also mean a change in directon.
Even though a change in speed changes velocity, a change in velocity does not necessarily 
   lead to a change in direction. 
** Define   
Speed does not change direction.
** Example/Explanation 
   Velocity is a combination of speed and direction. One can change speed without
  changing direction. Similarly, direction can be altered withouta change in speed. 

b. He flys like a bird and flaps his wings
** Identify:
    Some might think that since superman is mistaken for a bird when he flys,
    he flaps his "wing"s like a bird too.
** Define:
    This is false, superman does not flap his wings like a bird but only
    looks like a bird from far away.
** Example/Explanation
  Whenever superman is in a closeup, he is seen with his arms ourstretched.
** Non-Trivial Test question
  His flying is not based on aerodynamics so it is unecessary for him to flap
  his wings. 

c. He levitates, he's an alien "HEELLLLLOOOO!"
** Identify
  Some believe that superman levitates.
** Define
 This must be true, superman is levitating.
** Example/Explanation
  Since superman's flight is not based on aerodynamics, and he's not jumping, he is levitating.
  In one shot, superman is seen floating in the sky with Louis Lane. 

d. Why do I care about Superman again, he's in the D.C. universe ... so dark and terrible movies!
** Identify 
Some people are forgetting the significance of superman because D.C. makes dark movies and unfortunately
  superman is in the D.C. universe. People are judging superman based on the universe he is in. Since D.C. doesn't make good
  movies, the public would say "What good can come from D.C?"
** Define 
 Judging a character based on their environment is faulty logic. 
** Example/Explanation
Superman was once a beloved hero when he was first created. Superman came about as a personification of America and its role
in World War II. Superman gave people hope and gave something for soldiers and the public to read to forget about their troubles.
I believe that the D.C. universe is a good place for superman to be. His bright costume and good intentions strongly contrast
with D.C.'s dark and hostile flavor.
Take Joseph who was sold to Potipher for example. Joseph, in prison, was in a dark and terrible place. This environment
with all of its temptations made Joseph's riteousness and perseverance all the brighter. 



** Contrapositive

  Exchanging the hypothesis and conclusion of a conditional statement and negating both.

** Converse

  Exchanging the hypothesis and conclusion of a conditional statement.

** Inverse

  The negation of both the hypothesis and conclusion of a conditional statement.

** R: real numbers

  Irrational numbers, Rational numbers, Integers, Whole and natural numbers.

** Z: integers

Whole numbers (negative and positive) including zero.

** Q: rational numbers

Integers and fractions (numbers between whole numbers).

** Predicate

A predicate is an expression of one or more variables defined on a domain.

** Domain

The set of all possible inputs for a function.

** CoDomain

The set of all possible outputs for a function.

** Quantifier

The logical symbol which makes an assertion about a set. (Such as the Universal 
quantifier and the Existential quantifier.)

** Antecedent

  The first half of a hypothetical proposition, whenever the if-clause comes before the then-clause.

** Consequent

  The second half of a proposition, whenever it's the then-clause.

** Set

  A collection of objects in which objects are seperate entities.

** Fallacy

  An argument that is not valid (the premises are not true)

** Biconditional

  a relationship between two propositions that is true only when both propositions are simultaneously true or false 

** Sufficient Condition

  Means that the conclusion follows automatically when this condition is met. 

** Necessary Condition

  A condition that is required to for the conclusion to happen but doesn't mean that it will happen (There could be other requirements needed).

** ~p

  The negation of p.

** p ^ q

  The conjunction (or intersection) of p and q. (AND gate)

** p ∨ q

  The disjunction (or union) of p and q. (Or gate)

** p XOR q

Exclusive or and symetric difference of p and q. p or q but not both.

** p == q

Logical equivalence.

** p -> q

p is sufficent for q. P is a subset of q.

** p <--> q

biconditional: p if and only if q. P is sufficient for q; and vice versa. True when p and q have the same truth value.

** Three Dots in a Triangle

  A symbol to denote "therefore" at the end of a mathmatical proof.
  eg. The book of Mormon is the word of God \therefore Joesph Smith is a prophet of God.

** Upside Down A

Universal quantification. The predication of a property for every member in a domain. Interpreted as: “Given any…” of “For all…”

** Backwards E

Existential quantification. Says “There exists..” or “There’s at least one.”

** Union

 Is the set with all the members from two or more sets.

** Intersection

Is the set with members in common from two or more sets.

** Commutative Laws



** Associative Laws



** Distributive Laws



** Identity Laws



** Negation Laws



** Double Negative Law



** Idempotent Laws



** Universal Bound Laws



** De Morgan's Laws

  A set of transformation rules that apply to boolean logic.

** Absorption Laws

  When a variable in a proposition becomes irrevelent. Example: The set of the union of any set with the universal set is the universal set.  

** Negations of t and c



** Vacuously True

  A statement that asserts that all members in the empty set have a certain
  property. 

** Modus Ponens

  A Latin term for "mode that affirms by affirming".
  In terms of logic; p \rightarrow q , p is t \rightarrow q
  eg: If today is Thursday, the best students will attend discrete mathmatics.
      Today is Thursday! Thus, the best students will attend discrete mathmatics.

** Modus Tollens

  A Latin term for "mode that denies by denying".
  In terms of logic; p \rightarrow q , \neg q \rightarrow \neg p
  eg: If you buy nachoes at the movies, you won't need popcorn.
      You needed popcorn, so you didn't buy the nachoes.

** Elimination: valid argument form

  Using the process of elimanation to show whether something is t or nil.
  p∨q    p∨q
  \neg p    \neg q
  \therefore q   \therefore p

** Transitivity: Valid Argument form

  Transitive reasoning is a valid argument form that allows us to apply the transitive property to logic.
    p \rightarrow q
    q \rightarrow r
  \therefore p \rightarrow r     

