#+TITLE: Project00 Key_Terms
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+OPTIONS: html-postamble:nil
#+STARTUP: showeverything entitiespretty

NOTE: Be sure, when you are searching that they are logical defintions, that is
they are definitions that relate to math and Logic.

Example
* Superman Cannot be jumping really high
** identify
Superman is sometimes debated around his flying abilities
Some say that he is merely jumping and due to his speed and 
strength it appears to you and I that he is merely jumping and
moving his body to go up and down after that.
** Define
This is obviously false.  Superman is indeed levitating and not
Jumping
** Example/Explanation
If Superman were jumping when he catches Lois Lane she would be cut in half
due to the speed and trajectory of superman being the man of steel. This is because
he would have to slow/stop to the same speed as Lois to catch her and then "rejump".
He visually does not appear to be 'rejumping' and Lois isnt cut in half.  DONE!
** Non-Trivial Test question
What would be the best way to describe Superman's flight


a. He jumps and with his strength and speed is able to alter his path
** Identify:
Some people are mistaking a change in speed to also mean a change in directon.
Even though a change in speed changes velocity, a change in velocity does not necessarily 
   lead to a change in direction. 
** Define   
Speed does not change direction.
** Example/Explanation 
   Velocity is a combination of speed and direction. One can change speed without
  changing direction. Similarly, direction can be altered without a change in speed. 

b. He flys like a bird and flaps his wings
** Identify:
    Some might think that since superman is mistaken for a bird when he flys,
    he flaps his "wing"s like a bird too.
** Define:
    This is false, superman does not flap his wings like a bird but only
    looks like a bird from far away.
** Example/Explanation
  Whenever superman is in a closeup, he is seen with his arms ourstretched.
** Non-Trivial Test question
  His flying is not based on aerodynamics so it is unecessary for him to flap
  his wings. 

c. He levitates, he's an alien "HEELLLLLOOOO!"
** Identify
  Some believe that superman levitates.
** Define
 This must be true, superman is levitating.
** Example/Explanation
  Since superman's flight is not based on aerodynamics, and he's not jumping, he is levitating.
  In one shot, superman is seen floating in the sky with Louis Lane. 

d. Why do I care about Superman again, he's in the D.C. universe ... so dark and terrible movies!
** Identify 
Some people are forgetting the significance of superman because D.C. makes dark movies and unfortunately
  superman is in the D.C. universe. People are judging superman based on the universe he is in. Since D.C. doesn't make good
  movies, the public would say "What good can come from D.C?"
** Define 
 Judging a character based on their environment is faulty logic. 
** Example/Explanation
Superman was once a beloved hero when he was first created. Superman came about as a personification of America and its role
in World War II. Superman gave people hope and gave something for soldiers and the public to read to forget about their troubles.
I believe that the D.C. universe is a good place for superman to be. His bright costume and good intentions strongly contrast
with D.C.'s dark and hostile flavor.
Take Joseph who was sold to Potipher for example. Joseph, in prison, was in a dark and terrible place. This environment
with all of its temptations made Joseph's riteousness and perseverance all the brighter. 



* Contrapositive
** Define
   Exchanging the hypothesis and conclusion of a conditional statement and negating both.
** Example
   "If it is raining then the grass is wet"~ "If the grass is not wet then it is not raining"

** Non-Trivial Test Question
   
* Converse
** Define
   Exchanging the hypothesis and conclusion of a conditional statement.
** Example
   "If it is raining then the grass is wet"~ "If the grass is wet then it is raining"
** Non-Trivial Test Question

* Inverse
** Define
   The negation of both the hypothesis and conclusion of a conditional statement.
** Example
   "If it is raining then the grass will be wet"~ "If it is not raining then the grass will not be wet."
** Non-Trivial Test Question

* R: real numbers
** Define
   Irrational numbers, Rational numbers, Integers, Whole and natural numbers.
** Example
   -1 or 2 or even \pi. 
** Non-Trivial Test Question

* Z: integers
** Define
   Whole numbers (negative and positive) including zero.
** Example
   {...,-1,0,1,...} 
** Non-Trivial Test Question

* Q: rational numbers
** Define
   Integers and fractions (numbers between whole numbers).
** Example
   Q = {a/b, a and b \in Z and b\ne 0}
** Non-Trivial Test Question

* Predicate
** Define
   A predicate is an expression of one or more variables defined on a domain.
** Example
   P: X\rightarrow {t, nil}
** Non-Trivial Test Question

* Domain
** Define
The set of all possible inputs for a function.
** Example
   {(2,-3)(4,6)(3,-1)(6,6)(2,3)}
   Domain: {2,3,4,6}
** Non-Trivial Test Question

* CoDomain
** Define
   The set of all possible outputs for a function.
** Example
   x \rightarrow 2x+1
** Non-Trivial Test Question

* Quantifier
** Define
The logical symbol which makes an assertion about a set. (Such as the Universal 
quantifier and the Existential quantifier.)
** Example
   There exists, for all
** Non-Trivial Test Question

* Antecedent
** Define
  The first half of a hypothetical proposition, whenever the if-clause comes before the then-clause.
** Example
   If it rains
** Non-Trivial Test Question

* Consequent
** Define
   The second half of a proposition, whenever it's the then-clause.
** Example
   Then it will rain
** Non-Trivial Test Question

* Set
** Define
   A collection of objects in which objects are seperate entities.
** Example
   A table that has a book, plate, and a pencil on it.
** Non-Trivial Test Question

* Fallacy
** Define
   An argument that is not valid, either due to incorrect premises, an invalid conclusion,
   or specious reasoning.
** Example
   Penguins are black and white. 
   Citizen Kane is in black and white. 
   Therefore; Some penguins are actually Citizen Kane. 
** Non-Trivial Test Question

* Biconditional
** Define
   A relationship between two propositions that is true if and only if both propositions are simultaneously true or false 
** Example
   A rectangle is a square if and only if it's sides are all the same length.
   In logical notation, p<->q
   An angle is right iff it measures 90\deg.
** Non-Trivial Test Question

* Sufficient Condition
** Define
   Means that the conclusion follows automatically when this condition is met. 
** Example
   Being able to vote is sufficient to say that someone is at least 18.
** Non-Trivial Test Question

* Necessary Condition
** Define
   A condition that is required to for the conclusion to happen but doesn't mean that it will happen (There could be other requirements needed).
** Example
   Being at least 18 is necessary to be able to vote.
** Non-Trivial Test Question

* ~p
** Identify
   The negation symbol, applied to p
** Define
   The logical opposite of the given condition.
** Example
   The negation of the statement "It is raining" is "It is not raining"
** Non-Trivial Test Question

* p ^ q
** Identify
   The conjunction (or intersection) symbol, here applied to p and q.
** Define
   The conjunction is the set of objects that are members of both p and q and the logical
   condition where a conclusion can be true only if both p and q are true.
** Example
   If p is a set of fruit and q is a set of things that are yellow, 
   p ^ q would be the set of things that are both yellow and fruit, such as bananas.
** Non-Trivial Test Question

* p ∨ q
** Identify
   The disjucntion (or union) symbol, here applied to p and q.
** Define
   The disjunction is the set of objects that are members of either p or q and the logical
   condition where a conclusion is true as long as either p or q is true.
** Example
   If p is a set of fruit and q is a set of things that are yellow,
   p V q would be the set of things that are either fruit, yellow, or both.
   Such as apples, bananas, and corn.
** Non-Trivial Test Question

* p XOR q
** Identify
   The exclusive-or or symetric difference operator, here applied to p and q.
** Define
   The symetric difference is the set of objects that are either members of p or members of q,
   but not members of both and the logical condition where the conlusion is true as long as either
   p or q is true, but not both.
** Example
   If p is a set of fruit and q is a set of things that are yellow,
   p XOR q would be the set of things that are either fruit or yellow, but not both.
   Such as Apples and Corn, but not Bananas.
** Non-Trivial Test Question

* p == q
** Identify
   The logical equivalence operator/symbol.
** Define
   The logical equivalence operator states that the operands are the same.
** Example
   If p is a set of fruit, then q is the same set, with all of the same objects within it.
** Non-Trivial Test Question

* p -> q
** Identify
   The implication or if/then logical connective, here applied to p and q.
** Define
   The implication logical connective states that if p is true then q is true, that p is sufficent for q,
   and that p is a subset of q.
** Example
   The statement "If it is raining, then I need an umbrella"
   If p is the set of fruit, q can be the set of produce, which means p is a subset of q.
** Non-Trivial Test Question

* p <--> q
** Identify
   The biconditional, IFF, or if-and-only-if logical connective, here applied to p and q.
** Define
   The biconditional logical connective states that p is true if and only if q is true and
   that p is both necessary and sufficient for q. 
** Example 
   Squares are rectangles if and only if they have four sides of equal length.
** Non-Trivial Test Question

* Three Dots in a Triangle
** Identify
   The Therefore or Conclusion symbol
** Define
   A symbol that denotes "therefore" at the conclusion of a mathmatical proof or logical argument.
** Example
   Rectangles are polygons
   Squares are rectangles
   ∴ Squares are polygons
** Non-Trivial Test Question

* Upside Down A
** Identify
   The Universal Quantifier
** Define
   The Universal Quantifier is given for properties of every member of a domain as in, "For all..." and "Given any..."
** Example
   ∀ x: P(x) means that the function p(x) is true for all values of x in the domain. 
   For all objects in the set of fruit, the sugar content value is greater than 0
** Non-Trivial Test Question

* Backwards E
** Identify
   The Existential Quantifier
** Define
   The Existential Quantifies is given for properties that exist within a domain as in "There exists..." and "There is at least one.."
** Example
   ∃ x: P(x) means that the function p(x) is true for at least one value of x within the domain.
   At least one of the objects in the set of fruit is yellow.
** Non-Trivial Test Question

* Union
** Define
   The Union is the set with all the members from two or more sets.
** Example
   The union of p and q (p∪q) is the set of all objects that are within p or q.
   If p is the set of fruits and q is the set of things that are yellow, p∪q is the set
   of things that are either fruit, yellow, or both.
** Non-Trivial Test Question

* Intersection
** Define
   The intersetion ss the set where the members are those that two or more sets have in common.
** Example
   The intersection of p and q (p∩q) is the set of all objects that are in both p and q.
   If p is the set of fruit and q is the set of thins that are yellow, p∩q is the set of
   things that are both fruit and yellow.
** Non-Trivial Test Question

* Commutative Laws
** Define
   two valid rules of replacement, allowing the transposition of propositional variables within
   the logical expressions.
** Example 
*** Commutativity of Conjunction
   (P ^ Q) <=> (Q ^ P)
*** Commutativity of Disjunction
   (P V Q) <=> (Q V P)
*** Commutativity of Implication (Law of Permutation)
   (P->(Q->R)) <->(Q->(P->R))
*** Commutativity of Equivalence (Complete Commutative Law of Equivalence)
   (P<->Q)<->(Q<->P)
** Non-Trivial Test Question

* Associative Laws
** Define
   The assoicative laws allow for the movement of parentheses within logical expressions
*** Associativity of Disjunction
 ((P V Q) V R) <-> (P V (Q V R))
*** Associativity of Conjunction
 ((P \land Q) \land R) <-> (P \land (Q \land R))
*** Associativity of Equivalences
 ((P <-> Q) <-> R) <-> (P <-> (Q <-> R))
** Example

** Non-Trivial Test Question

* Distributive Laws
** Define
   The distributive laws expand individual occurances of certain logical connectives, 
   within some formula, into separate applications of those connectives across 
   subformulas of the given formula
** Example
*** Distribution of Conjunction Over Conjunction
    (P ^ (Q ^ R)) <-> ((P ^ Q) ^ (P ^ R))
*** Distribution of Conjunction Over Disjunction
    (P ^ (Q V R)) <-> ((P ^ Q) V (P ^ R))
*** Distribution of Disjunction Over Conjunction
    (P V (Q ^ R)) <-> ((P V Q) ^ (P V R))
*** Distribution of Disjunction Over Disjunction
    (P V (Q V R)) <-> ((P V Q) V (P V R))
*** Distribution of Implication
    (P -> (Q -> R)) <-> ((P -> Q) -> (P -> R))
*** Distribution of Implication Over Equivalence
    (P -> (Q <-> R)) <-> ((P -> Q) <-> (P -> R))
*** Distribution of Disjunction Over Equivalence
    (P V (Q <-> R)) <-> ((P V Q) <-> (P V R))
*** Double Distribution
    ((P \land Q) \lor (R \land S)) <-> (((P \lor R) \land (P \lor S)) \land ((Q \lor R) \land (Q \lor S)))
    ((P \lor Q) \land (R \lor S)) <-> (((P \land R) \lor (P \land S)) \lor ((Q \land R) \lor (Q \land S)))   
** Non-Trivial Test Question

* Identity Laws
** Define
   The identity laws are used to show that given a tautology or a contradiction and a logical
   statement, the identiy of the statement can be confirmed through ANDing and ORing.
** Example
*** p \wedge  T ≡ p
    This identity law says that any logical statement, when ANDed with a tautology, will
    be identical/equivalent to the original statement. 
*** p ∨ F ≡ p
    This identity law says that any logical statment, when ORed with a contradiction, will
    be identical/equivalent to the original statement.
** Non-Trivial Test Question

* Negation Laws
** Define

** Example

** Non-Trivial Test Question

* Double Negative Law
** Define
   \not \not p \equiv p
** Example
   If we take the negation of a statement. "It is raining", we get the statement, "It is not
   raining." If we then take the negation of our new statement, we return to the original,
   "It is raining."
** Non-Trivial Test Question

* Idempotent Laws
** Define
   The idempotent laws refer to idempotent (or redundant) statements. Where ANDing and ORing
   a logical statement with itself returns a result that is identical/equivalent to the 
   original statement.
** Example
   p ∧ p ≡ p 
   p ∨ p ≡ p
** Non-Trivial Test Question

* Universal Bound Laws
** Define
   The intersect of any set with the empty set an the empty set.
   The union of any set with the universal set is the universal set.
** Example
   A \lor Universal \equiv Universal
   A \land EmptySet \equiv EmptySet
** Non-Trivial Test Question

* De Morgan's Laws
** Define
   A set of transformation rules that apply to boolean logic.
** Example
   ¬(p ∧ q) ≡ ¬p ∨ ¬q
   ¬(p ∨ q) ≡ ¬p ∧ ¬q
** Non-Trivial Test Question

* Absorption Laws
** Define
   The absorption laws show the base cases when a variable in a proposition becomes irrevelent 
** Example
   p ∨ (p ∧ q) ≡ p
   p ∧ (p ∨ q) ≡ p     
** Non-Trivial Test Question

* Negations of t and c
** Define
   The negation for the statement t \land c.
   \not t \lor \not c
** Example
   Given the statement t= I am rich, and c = I am happy
   t and c states that "I am rich and I am happy". which evaluates as true only if I am both
   rich and happy.
   The negation of this would be "I am not rich or I am not happy", which as a valid negation,
   evaluates to true as long as you are not both rich and happy.
** Non-Trivial Test Question

* Vacuously True
** Define
   A statement that asserts that all members in the empty set have a certain
   property. 
** Example
   If our set is an empty apple box, it can truthfully be said that all of the apples in the
   box are green. 
** Non-Trivial Test Question

* Modus Ponens
** Define
   A Latin term for "mode that affirms by affirming".
   In terms of logic: 
   p \rightarrow q 
   p 
   ∴ q
** Example
   If today is Thursday, the best students will attend discrete mathmatics.
   Today is Thursday!
   Therefore, the best students will attend discrete mathmatics.
** Non-Trivial Test Question

* Modus Tollens
** Define
   A Latin term for "mode that denies by denying".
   In terms of logic: 
   p \rightarrow q  
   \neg q
   ∴ \neg p
** Example
   If you buy nachos at the movies, you won't need popcorn.
   You needed popcorn 
   Therefore: You didn't buy the nachos.
** Non-Trivial Test Question

* Elimination: valid argument form
** Define
   Using the process of elimanation to reach a conclusion.
   p∨q
   \neg p
   \therefore q
** Example
   The student is either passing or failing discrete math.
   The student is not failing discrete math.
   Therefore: The student is passing discrete math.
** Non-Trivial Test Question

* Transitivity: Valid Argument form
** Define
   Transitive reasoning is a valid argument form that allows us to apply the 
   transitive property to logic.
   p \rightarrow q
   q \rightarrow r
   \therefore p \rightarrow r     
** Example
   Dogs are animals
   Animals are alive
   Dogs are alive.
** Non-Trivial Test Question
   
