#+TITLE: Project00 Key_Terms
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+OPTIONS: html-postamble:nil
#+STARTUP: showeverything entitiespretty

NOTE: Be sure, when you are searching that they are logical defintions, that is
they are definitions that relate to math and Logic.

Example
* Superman Cannot be jumping really high
** identify
Superman is sometimes debated around his flying abilities
Some say that he is merely jumping and due to his speed and 
strength it appears to you and I that he is merely jumping and
moving his body to go up and down after that.
** Define
This is obviously false.  Superman is indeed levitating and not
Jumping
** Example/Explanation
If Superman were jumping when he catches Lois Lane she would be cut in half
due to the speed and trajectory of superman being the man of steel. This is because
he would have to slow/stop to the same speed as Lois to catch her and then "rejump".
He visually does not appear to be 'rejumping' and Lois isnt cut in half.  DONE!
** Non-Trivial Test question
What would be the best way to describe Superman's flight


a. He jumps and with his strength and speed is able to alter his path


b. He flys like a bird and flaps his wings


c. He levitates, he's an alien "HEELLLLLOOOO!"


d. Why do I care about Superman again, he's in the D.C. universe ... so dark and terrible movies!

Contrapositive

Converse

inverse

R: real numbers

Z: integers

Q: rational numbers

predicate

Domain

CoDomain

quantifier

antecedent - The first half of a hypothetical proposition, whenever the if-clause comes before the then-clause.

consequent - The second half of a proposition, whenever it's the then-clause.

Set  - A collection of objects in which objects are seperate entities. 

Fallacy  -  An argument that is not valid (the premises are not true). 

biconditional - a relationship between two propositions that is true only when both propositions are simultaneously true or false. 

sufficient condition - Means that the conclusion follows automatically when this condition is met.

necessary condition - A condition that is required to for the conclusion to happen but doesn't mean that it will happen (There could
                       be other requirements needed).

~p - The negation of p.

p ^ q      - The Conjunction of p and q. (And gate)

p V q       - The disjunction of p and q. (Or gate)

P XOR q     -   Exclusive or and symetric difference of p and q. p or q but not both. 

p == q       -      Logical equivalence. 

p -> q     -      p is sufficent for q. P is a subset of q.  

P <--> q      -  biconditional: p if and only if q. P is sufficient for q; and vice versa. True when p and q have the same truth value. 

Three dots in a triangle

upside down A

Backwards E

union - Is the set with all the members from two or more sets.

intersection - Is the set with members in common from two or more sets.

Commutative laws

associative laws

distributive laws

identy laws

negation laws

double negative law

idempotent laws

universal bound laws

De morgan's laws

absoption laws

negations of t and c

vacuously true

Modus Ponens

Modus Tollens

Elimination: valid argument form

Transitivity: Valid Argument form
