#+TITLE: Special Projects
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+OPTIONS: html-postamble:nil
#+STARTUP: showeverything entitiespretty

NOTE: You must get this approved by Brother Benning.

* Special Project
On exercises-versus-problems.org, it is talking about the differences and benefits of 
 exercises versus problems. It descibes exercises as being more methodical and requiring
 less mental effort than problems even if they keep one's brain or body suited for a 
 specific task. Along with that, it explains how problems require us to think and operate 
 different from how we would normally. They require more thinking, work, and/or 
 experimentation. They often require making mistakes before one obtains success whereas 
 exercises are in one's realm of familiarity and experience allowing one to rely more on 
 memory and practice in order to succeed. Overall, the purpose of 
 exercises-versus-problems.org is to show how problem-solving is more challenging, 
 productive, and growth-inducing than repeated exercises.

APPROVED PUZZLES AND PROBLEMS

1. Week02 teach.org puzzle of the hats.
  The third student knew the color of her hat and was able to prove it. The color of her hat 
  is white. If her hat was red, the second student should have been able to quess that his 
  hat was white if the first student said he did not know his own hat color. 

2. You are on an Island where there are only two types of individuals besides yourself, 
   Knaves and Knights.  You have the following encounters with natives.
  
  a. Two natives A and B address you as follows: A says: Both of us are Knights. B says: A is a knave.  What are A and B?
    ANSWER: A is a knave, B is a knight.
  b. Another two natives C and D approach you but only C speaks.  C says: Both of us are knaves.  What are C and D?
    ANSWER: C is a knave, D is a knight.
  c. You then encounter natives E and F. E says F is a knave. F says: E is a knave.  How many knaves are there?
    ANSWER: There is one knave.
  d. Finally you meet a group of six natives, U,V,W,X,Y,and Z, who speak to you as follows: U says: None of us is a knight. V says: at     least three of us are knights. W says: At most three of us are knights. X says: exactly five of us are knights. Y says: Exactly
  two of  us are knights. Z says: Exactly one of us is a Knight. Which are Knights and which are knaves?
    ANSWER: U is a knave, V is a knave, W is a knight, X is a knave, Y is a knight, Z is a knave.

3. Given the following information about a computer program, find the mistake in the program.
  a. There is an undeclared variable or there is a syntax error in the first five lines.
  b. If there is a syntax error in the first five lines, then there is a missing semicolon or a variable name is misspelled.
  c. There is not a missing semicolon.
  d. There is not a misspelled variable name.
  
  ANSWER: There is an undeclared variable.

4. Sharky, a leader of the underworld, was killed by one of his own band of four henchmen.
   Detective Sharp interviewed the men and determined that all were lying except for one.  
   He deduced who killed sharky on the basis of the following statements:
  
  a. Socko: Lefty killed Sharky.
  b. Fats: Muscles didn’t kill Sharky.
  c. Lefty: Muscles was shooting craps with Socko when Sharky was knocked off.
  d. Muscles: Lefty didn’t kill Sharkky. 

Socko cannot have told the truth. If so both Lefty and Muscles would have to have killed Sharky due to statement a and b
Fats  cannot have told the truth, because a and d can't both be lies.
Lefty cannot have told the truth, because a and d can't both be lies.
Muscles must have told the truth, which means he killed Sharky, Lefty is innocent, and he wasn't shooting craps with Socko

  Who killed Sharky?

  ANSWER: Muscles

5. Balance
  One morning, I observed Holmes rolling a shilling back and forth over his knuckles, from one 
  finger to the next, with his other hand held behind his back. "You can do a lot of mischief 
  with a tricked coin, old friend,” he said. 
  “That looks real enough to me,”  I replied. 
  “This? Oh, it is.  But surely you have heard of gamblers’ coins that are cunningly weighted 
  to favour heads over tails, or vice versa?” 
  I allowed that I had indeed. 
  “Such devices are nasty trap for the unwary. But it is possible to get a totally unbiased either/or result from any weighted coin.” 
  “Oh?” “Indeed.  Can you tell me how?” 
  
  Can ​YOU​ work it out?
 
  ANSWER:
  
  This problem is only possible if the coin is weighted so that it can land on both sides at least some of the time. (If it always lands
  on heads or tails there can never be a fair toss.)
  
  Assuming that the coin lands heads up 75% of the time instead of 50%, then a single flip cannot be unbiased, as it will be 75/25 instead
  of 50/50. So multiple flips will be required.

  The odds out of two flips are normally
  | HH | HT | TH | TT |
  | 25 | 25 | 25 | 25 |

  But in our weighted case will be
  |  HH   |  HT   |  TH   |  TT  |
  | 56.25 | 18.75 | 18.75 | 6.25 |
  
  Looking at the weighted case, it becomes clear that the HT and TH are equally likely.
  
  This is correct even if tails is the weighted side or if the weight is more than 75%
  For example with Heads at 20% and Tails at 80%:
  | HH | HT | TH | TT |
  |  4 | 16 | 16 | 64 |

  This means that there is an equal probability of calling heads than tails as tails then heads
  So no matter what the weight of the coin or in which direction, an unbiased result can be achieved
  if each person calls out either HT or TH and then flips the coin twice, discarding HH and TT results.

6. THE BEAST
   2.0 Back-Story: Several anthropology PhD candidates will each publish a dissertation this year about a different aboriginal culture
      they've been living with and studying. Match each student to the culture they've written about and the country in which it is
      located, and determine the month in which each dissertation will be published. 

Candidates: Ollie, Michael, Doreen, Yvette, Floyd, Sonja, Keith
Culture: Haleyito, Burutia, Warith, Eldang, Xozix, Yersim
Country: Quatar, Pakistan, Denmark, Romania, Haiti, Oman
Month:

1.​ The student who has been studying the Haleyito culture will publish sometime after the student 
      who has been working in Qatar.
2.​ The student who has been working in Pakistan will publish 1 month after Ollie.
3.​ Michael hasn't been studying the Burutia culture.
4.​ The person who has been studying the Warith culture will publish 1 month before the student 
      who has been working in Denmark.
5.​ The student who has been working in Denmark will publish 2 months before Doreen.
6.​ The student who has been studying the Eldang culture will publish 2 months before the student
      who has been studying the Xozix culture.
7.​ Yvette is either the student who has been working in Qatar or the person who has been working
      in Romania.
8.​ The student who has been working in Denmark will publish 4 months before the person who has 
      been working in Haiti.
9.​ Floyd will publish in January.
10.​ Floyd will publish 5 months before Sonja.
11.​ Sonja hasn't been studying the Yersim culture.
12.​ Of the person who has been studying the Haleyito culture and the student who has been working
      in Oman, one is Keith and the other is Michael.
13.​ Sonja hasn't been studying the Burutia culture.
14.​ Michael will publish 2 months after Yvette.
15.​ The person who has been studying the Eldang culture will publish 1 month after the student 
      who has been studying the Warith culture. 
 
Remember as with Beast 1.0 there will be Names/Cultures/Countries not mentioned in the hints. X,Y,Z work fine. 
 
https://docs.google.com/spreadsheets/d/1LXBfjvFP8AStAlmhH5o0Qxxj6sei0Tx0MeRlbdDFdnc/edit?usp=sharing

| Month     | Candidate | Culture | Country |

| January   | Floyd     | X        | Romania  |
| February  |           |          |          |
| March     |           |          |          |
| April     |           |          |          |
| May       | Keith     | Warith   | Oman     |
| June      | Sonja     | Eldang   | Denmark  |
| July      |           |          |          |
| August    | Doreen    | Xozix    | Y        |
| September | Yvette    | Yersim   | Quatar   |
| October   | Ollie     | Burutia  | Haiti    |
| November  | Michael   | Haleyito | Pakistan |
| December  |           |          |          |

This is one possible solution
